pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                bat 'mvn clean package'
            }
            post{
                success{
                    archiveArtifacts artifacts:'**/target/*.war'
                }

            }

        }
        stage('Deployed in staging') {
            steps {
              echo 'Deployed in staging..'
              currentBuild job:'deployed-in-staging',wait: true
            }
        }
    }
}